# Single image for the whole NSW Agency service: builds the frontend, ships it
# next to the Go binary, and serves both the API and the SPA from one process.
# This is the ONLY Dockerfile — backend/ and frontend/ no longer build separately.
#
# Build context is the repo ROOT (so both backend/ and frontend/ are reachable):
#   docker build -t nsw-agency .
#
# Runtime config (/runtime-env.js, window.__APP_CONFIG__) is generated by the Go
# server per request from the environment — no entrypoint script, no file is
# written at runtime.

# ---- Stage 1: build the frontend SPA -----------------------------------------
FROM node:22-bookworm-slim AS frontend-builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app

RUN corepack enable

COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

COPY frontend/ .

RUN pnpm build

# ---- Stage 2: build the Go binaries ------------------------------------------
FROM golang:1.25-bookworm AS backend-builder

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

# -ldflags="-s -w" strips the symbol table and DWARF debug info to shrink the
# binaries. Go panic traces (function + line) and pprof still work, since they
# use the runtime pclntab rather than the symbol table.
RUN go build -ldflags="-s -w" -o /out/agency ./cmd/server \
  && go build -ldflags="-s -w" -o /out/migrate ./cmd/migrate \
  && go build -ldflags="-s -w" -o /out/nswac ./cmd/cli

ARG NSW_SRILANKA_REF=main
RUN git clone --depth 1 --branch ${NSW_SRILANKA_REF} https://github.com/OpenNSW/nsw-srilanka /out/nsw-srilanka

# ---- Stage 3: runtime --------------------------------------------------------
FROM debian:bookworm-slim

LABEL org.opencontainers.image.source="https://github.com/OpenNSW/nsw-agency"
LABEL org.opencontainers.image.description="NSW Agency service (backend API + officer portal)"

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && useradd -u 1001 -r -s /bin/false -d /app appuser \
  && mkdir -p /app /app/web /data \
  && chown -R appuser:appuser /data /app

WORKDIR /app

# Go binaries
COPY --from=backend-builder --chown=appuser:appuser /out/agency /app/agency
COPY --from=backend-builder --chown=appuser:appuser /out/migrate /app/migrate
COPY --from=backend-builder /out/nswac /usr/local/bin/nswac
COPY --from=backend-builder --chown=appuser:appuser /app/migrations /app/migrations
COPY --from=backend-builder --chown=appuser:appuser /app/data/task-configs /app/data/task-configs
COPY --from=backend-builder --chown=appuser:appuser /out/nsw-srilanka/configs /app/nsw-srilanka-configs

# Built frontend, served (read-only) by the Go binary. The server resolves its
# asset dir as "web" relative to WORKDIR (/app), so it must land at /app/web.
# /runtime-env.js is generated dynamically from the environment, so nothing is
# written into this directory at runtime.
COPY --from=frontend-builder --chown=appuser:appuser /app/dist /app/web

ENV TASK_CONFIGS_DIR=/app/data/task-configs
ENV FORM_TEMPLATES_DIR=/app/nsw-srilanka-configs

# Runtime settings — UID 1001 matches appuser, OpenShift-compatible
USER appuser

# Single port serves both API and SPA (override via PORT env var)
EXPOSE 8081

# No ENTRYPOINT: the migrate Job reuses this image by overriding CMD with
# ["/app/migrate","up"]; the default runs the agency server.
CMD ["/app/agency"]
